package com.sszt.cdslpetitionletter.bean

data class CaseListBean(
    val endRow: Int,
    val firstPage: Int,
    val hasNextPage: Boolean,
    val hasPreviousPage: Boolean,
    val isFirstPage: Boolean,
    val isLastPage: Boolean,
    val lastPage: Int,
    val list: ArrayList<CaseListItemBean>,
    val navigateFirstPage: Int,
    val navigateLastPage: Int,
    val navigatePages: Int,
    val navigatepageNums: List<Int>,
    val nextPage: Int,
    val pageNum: Int,
    val pageSize: Int,
    val pages: Int,
    val prePage: Int,
    val size: Int,
    val startRow: Int,
    val total: Int
)


data class CaseListItemBean(
    val applyAddress: Any,
    val applyIdentity: String,
    val applyLegalRepresentative: Any,
    val applyName: String,
    val applyOrganRepresentative: Any,
    val applyOtherNum: Any,
    val applyOtherType: Any,
    val applyPhone: Any,
    val applyStreet: Any,
    val applyType: Any,
    val applyUsci: Any,
    val caseAddress: Any,
    val caseAgentList: Any,
    val caseDate: String,
    val caseDesc: Any,
    val caseOrganization: String,
    val caseStatus: Int,
    val caseStreet: Any,
    val caseType: String,
    val createDate: String,
    val createUserName: Any,
    val createUserUuid: Any,
    val id: Any,
    val institutionName: Any,
    val respondentAddress: Any,
    val respondentIdentity: Any,
    val respondentLegalRepresentative: Any,
    val respondentName: Any,
    val respondentOrganRepresentative: Any,
    val respondentOtherNum: Any,
    val respondentOtherType: Any,
    val respondentPhone: Any,
    val respondentStreet: Any,
    val respondentType: Any,
    val respondentUsci: Any,
    val uuid: String
)